<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Futuristik, Pullman Bandung Grand Central_f91d8e</name>
   <tag></tag>
   <elementGuidId>2267915d-00d9-4714-bd52-1da66606219b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='___gcse_0']/div/div/div/div[5]/div[2]/div/div/div/div/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.gs-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1d01fb23-e7ad-409b-b683-0dad1d838763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gs-title</value>
      <webElementGuid>14df3feb-9dd6-4228-b5b2-447ddc9dc617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.google.com/url?client=internal-element-cse&amp;cx=partner-pub-9012468469771973:uc7pie-r3ad&amp;q=https://biz.kompas.com/read/2021/08/18/133238228/futuristik-pullman-bandung-grand-central-hadirkan-robot-berteknologi-ai-dan&amp;sa=U&amp;ved=2ahUKEwjfj4CDydSDAxUyxzgGHVu0AkcQFnoECAYQAg&amp;usg=AOvVaw0wqPkd5dz-Or2SF1dqlPjP</value>
      <webElementGuid>b733170e-325d-4655-a017-015546d44dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_parent</value>
      <webElementGuid>5a9daf1a-79a6-4173-8fce-124d323f2ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>7b71fd4d-e777-4abc-9a2a-f69f0d1d1d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cturl</name>
      <type>Main</type>
      <value>https://www.google.com/url?client=internal-element-cse&amp;cx=partner-pub-9012468469771973:uc7pie-r3ad&amp;q=https://biz.kompas.com/read/2021/08/18/133238228/futuristik-pullman-bandung-grand-central-hadirkan-robot-berteknologi-ai-dan&amp;sa=U&amp;ved=2ahUKEwjfj4CDydSDAxUyxzgGHVu0AkcQFnoECAYQAg&amp;usg=AOvVaw0wqPkd5dz-Or2SF1dqlPjP</value>
      <webElementGuid>91063a90-4bd3-414d-b131-be651d10e11f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctorig</name>
      <type>Main</type>
      <value>https://biz.kompas.com/read/2021/08/18/133238228/futuristik-pullman-bandung-grand-central-hadirkan-robot-berteknologi-ai-dan</value>
      <webElementGuid>eefa6821-b963-461b-b1b1-ca4aa71f3a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Futuristik, Pullman Bandung Grand Central Hadirkan Robot ...</value>
      <webElementGuid>57351aab-e4dd-427a-8bad-3fc759b669d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;___gcse_0&quot;)/div[@class=&quot;gsc-control-cse gsc-control-cse-en&quot;]/div[@class=&quot;gsc-control-wrapper-cse&quot;]/div[@class=&quot;gsc-results-wrapper-nooverlay gsc-results-wrapper-visible&quot;]/div[@class=&quot;gsc-wrapper&quot;]/div[@class=&quot;gsc-resultsbox-visible&quot;]/div[@class=&quot;gsc-resultsRoot gsc-tabData gsc-tabdActive&quot;]/div[@class=&quot;gsc-results gsc-webResult&quot;]/div[@class=&quot;gsc-expansionArea&quot;]/div[@class=&quot;gsc-webResult gsc-result&quot;]/div[@class=&quot;gs-webResult gs-result&quot;]/div[@class=&quot;gsc-thumbnail-inside&quot;]/div[@class=&quot;gs-title&quot;]/a[@class=&quot;gs-title&quot;]</value>
      <webElementGuid>5aa43214-9f71-46d6-a40a-f35f66d0816d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='___gcse_0']/div/div/div/div[5]/div[2]/div/div/div/div/div/div/div/a</value>
      <webElementGuid>0666d179-0ab6-452e-9e92-04469b3b74a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.google.com/url?client=internal-element-cse&amp;cx=partner-pub-9012468469771973:uc7pie-r3ad&amp;q=https://biz.kompas.com/read/2021/08/18/133238228/futuristik-pullman-bandung-grand-central-hadirkan-robot-berteknologi-ai-dan&amp;sa=U&amp;ved=2ahUKEwjfj4CDydSDAxUyxzgGHVu0AkcQFnoECAYQAg&amp;usg=AOvVaw0wqPkd5dz-Or2SF1dqlPjP')]</value>
      <webElementGuid>4a4965e8-d940-488e-bf74-17654af7bcd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/a</value>
      <webElementGuid>004128a2-c9ba-45d6-8580-cfa438a6754c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.google.com/url?client=internal-element-cse&amp;cx=partner-pub-9012468469771973:uc7pie-r3ad&amp;q=https://biz.kompas.com/read/2021/08/18/133238228/futuristik-pullman-bandung-grand-central-hadirkan-robot-berteknologi-ai-dan&amp;sa=U&amp;ved=2ahUKEwjfj4CDydSDAxUyxzgGHVu0AkcQFnoECAYQAg&amp;usg=AOvVaw0wqPkd5dz-Or2SF1dqlPjP' and (text() = 'Futuristik, Pullman Bandung Grand Central Hadirkan Robot ...' or . = 'Futuristik, Pullman Bandung Grand Central Hadirkan Robot ...')]</value>
      <webElementGuid>244f7d52-89ec-4926-b86b-cfa187f4d4b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
