<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Futuristik, Pullman Bandung Grand Centr_e94658</name>
   <tag></tag>
   <elementGuidId>0a081c2a-bafd-4f33-95d6-93905c79aa91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='___gcse_0']/div/div/div/div[5]/div[2]/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.gsc-webResult.gsc-result</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>402b1e6e-4dcc-4040-a155-62a98ef65d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gsc-webResult gsc-result</value>
      <webElementGuid>befa17c2-3805-412a-85c4-d10a54128bd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Futuristik, Pullman Bandung Grand Central Hadirkan Robot ...biz.kompas.comhttps://biz.kompas.com/.../futuristik-pullman-bandung-grand-central-hadirk...KOMPAS.com › read › 2021/08/18 › futuristik-...Futuristik, Pullman Bandung Grand Central Hadirkan Robot ...18 Aug 2021 ... Kini, pengalaman menginap di sebuah hotel yang kian futuristik tersebut bisa juga dirasakan di Tanah Air. Hotel mewah yang berada di bawah ...biz.kompas.comhttps://biz.kompas.com/.../futuristik-pullman-bandung-grand-central-hadirk...</value>
      <webElementGuid>451d50bc-0224-4043-92e6-343ba280fb3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;___gcse_0&quot;)/div[@class=&quot;gsc-control-cse gsc-control-cse-en&quot;]/div[@class=&quot;gsc-control-wrapper-cse&quot;]/div[@class=&quot;gsc-results-wrapper-nooverlay gsc-results-wrapper-visible&quot;]/div[@class=&quot;gsc-wrapper&quot;]/div[@class=&quot;gsc-resultsbox-visible&quot;]/div[@class=&quot;gsc-resultsRoot gsc-tabData gsc-tabdActive&quot;]/div[@class=&quot;gsc-results gsc-webResult&quot;]/div[@class=&quot;gsc-expansionArea&quot;]/div[@class=&quot;gsc-webResult gsc-result&quot;]</value>
      <webElementGuid>dd69a336-00cb-4931-ba42-028bd946f9ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='___gcse_0']/div/div/div/div[5]/div[2]/div/div/div/div</value>
      <webElementGuid>8363a893-3e29-4a2b-8293-0602402ebcfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div/div</value>
      <webElementGuid>66838bf4-cf33-41cb-9210-4aec819c7336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Futuristik, Pullman Bandung Grand Central Hadirkan Robot ...biz.kompas.comhttps://biz.kompas.com/.../futuristik-pullman-bandung-grand-central-hadirk...KOMPAS.com › read › 2021/08/18 › futuristik-...Futuristik, Pullman Bandung Grand Central Hadirkan Robot ...18 Aug 2021 ... Kini, pengalaman menginap di sebuah hotel yang kian futuristik tersebut bisa juga dirasakan di Tanah Air. Hotel mewah yang berada di bawah ...biz.kompas.comhttps://biz.kompas.com/.../futuristik-pullman-bandung-grand-central-hadirk...' or . = 'Futuristik, Pullman Bandung Grand Central Hadirkan Robot ...biz.kompas.comhttps://biz.kompas.com/.../futuristik-pullman-bandung-grand-central-hadirk...KOMPAS.com › read › 2021/08/18 › futuristik-...Futuristik, Pullman Bandung Grand Central Hadirkan Robot ...18 Aug 2021 ... Kini, pengalaman menginap di sebuah hotel yang kian futuristik tersebut bisa juga dirasakan di Tanah Air. Hotel mewah yang berada di bawah ...biz.kompas.comhttps://biz.kompas.com/.../futuristik-pullman-bandung-grand-central-hadirk...')]</value>
      <webElementGuid>e83e1ceb-b03b-45f6-a643-8be2fc3d33aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
