<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Login (1)</name>
   <tag></tag>
   <elementGuidId>0c55f022-6c63-4e2d-a422-dba0f068a7f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='txt_signin']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt_signin > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0c7033cf-36f8-46e5-856b-a26a2ac39fac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Login</value>
      <webElementGuid>3a1b01d0-c221-4de6-ae36-dd34d0f78688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_signin&quot;)/span[1]</value>
      <webElementGuid>cb6946ca-a8c7-4b20-9504-5e54858c6bb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='txt_signin']/span</value>
      <webElementGuid>78c73e3f-6e6d-43a7-9bf9-fb66e02ca324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/span</value>
      <webElementGuid>4e93074e-1793-4061-9792-2669b99f56b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Login' or . = ' Login')]</value>
      <webElementGuid>9674d9d3-cff7-4ddf-b9da-be24578763b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
