<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchResult1</name>
   <tag></tag>
   <elementGuidId>293c8694-a70d-46d6-8958-151d5b45ef00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div/div/div/div/div/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='___gcse_0']/div/div/div/div[5]/div[2]/div/div/div/div[2]/div/div/div/a</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0cec622b-c688-4b90-9a08-417fe834063e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gs-title</value>
      <webElementGuid>b68601e7-8469-4eec-8b24-eeed3965caea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.google.com/url?client=internal-element-cse&amp;cx=partner-pub-9012468469771973:uc7pie-r3ad&amp;q=https://www.kompas.com/tag/robot&amp;sa=U&amp;ved=2ahUKEwj12ZnG3dSDAxU0-TgGHVcYBjkQFnoECAkQAQ&amp;usg=AOvVaw1BlSyZA73A4YbgfME5m_9z</value>
      <webElementGuid>7ad6b7d2-ee92-4cf3-99dc-417ecad1351c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_parent</value>
      <webElementGuid>8cb6e897-179b-48fe-8a05-9d3f4c12261e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>af280f15-a215-4669-9a67-af89f75591fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cturl</name>
      <type>Main</type>
      <value>https://search.kompas.com/search/?q=robot&amp;submit=Submit#gsc.tab=0&amp;gsc.q=robot&amp;gsc.page=1&#xd;
</value>
      <webElementGuid>e4e451c4-5f13-4ec9-8e34-1956d9cf263d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctorig</name>
      <type>Main</type>
      <value>https://www.kompas.com/tag/robot</value>
      <webElementGuid>9fc32f62-27c2-4dc9-85e0-4a70ef7a9fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Berita Harian Robot Terbaru Hari Ini - Kompas.com</value>
      <webElementGuid>76cd6914-3437-4fb9-8eeb-b1883d6a050f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/a</value>
      <webElementGuid>2d7fa3a0-f437-48fd-ae60-b9028e2671bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div/a</value>
      <webElementGuid>b9825f9f-c33d-4336-9b93-928471a69084</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
