<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>endofArticle</name>
   <tag></tag>
   <elementGuidId>47c23f28-3bc9-445c-96b2-cbbb22cf73db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='EndOfArticle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#EndOfArticle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b7c36d66-42eb-4145-97a9-54304a2f688c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EndOfArticle</value>
      <webElementGuid>714c77cb-b3f2-4f23-a50e-0b0afe415cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-recent-on-screen2485677_1415</name>
      <type>Main</type>
      <value>5471</value>
      <webElementGuid>1b00e97f-e21d-475b-8031-278a24bcc6ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-first-on-screen2485677_1415</name>
      <type>Main</type>
      <value>5471</value>
      <webElementGuid>6dd6fc21-28bf-416b-bc10-2f872085fbb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-total-visible-time2485677_1415</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>b860aae6-cf96-4d2c-9a71-faa5f909071e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-has-fired2485677_1415</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>dd38d984-a601-41ab-9d20-458f70b74aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EndOfArticle&quot;)</value>
      <webElementGuid>1e040aa3-89a8-48c0-97b3-aea5279c0235</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='EndOfArticle']</value>
      <webElementGuid>da5330fe-5b7d-45db-9304-1f71ede33c04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[5]/div[2]/div/div/div</value>
      <webElementGuid>b9edeec1-e70a-4b59-ba6d-c80a405a3f9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'EndOfArticle']</value>
      <webElementGuid>87c41fa5-9fd5-4352-8b7e-2afcf2380ce3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
